// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dearrow.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listBranding = `-- name: ListBranding :many
SELECT video_id, title, original_title_won, thumbnail_time, original_thumb_won, random_time, has_submission, fetched_at FROM dearrow_branding WHERE video_id = ANY($1::text[])
`

// What is already known about these videos. The page asks once for all of them.
func (q *Queries) ListBranding(ctx context.Context, videoIds []string) ([]DearrowBranding, error) {
	rows, err := q.db.Query(ctx, listBranding, videoIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DearrowBranding{}
	for rows.Next() {
		var i DearrowBranding
		if err := rows.Scan(
			&i.VideoID,
			&i.Title,
			&i.OriginalTitleWon,
			&i.ThumbnailTime,
			&i.OriginalThumbWon,
			&i.RandomTime,
			&i.HasSubmission,
			&i.FetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertBranding = `-- name: UpsertBranding :exec
INSERT INTO dearrow_branding (
    video_id, title, original_title_won, thumbnail_time,
    original_thumb_won, random_time, has_submission, fetched_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, now())
ON CONFLICT (video_id) DO UPDATE
SET title              = EXCLUDED.title,
    original_title_won = EXCLUDED.original_title_won,
    thumbnail_time     = EXCLUDED.thumbnail_time,
    original_thumb_won = EXCLUDED.original_thumb_won,
    random_time        = EXCLUDED.random_time,
    has_submission     = EXCLUDED.has_submission,
    fetched_at         = now()
`

type UpsertBrandingParams struct {
	VideoID          string        `json:"video_id"`
	Title            string        `json:"title"`
	OriginalTitleWon bool          `json:"original_title_won"`
	ThumbnailTime    pgtype.Float8 `json:"thumbnail_time"`
	OriginalThumbWon bool          `json:"original_thumb_won"`
	RandomTime       float64       `json:"random_time"`
	HasSubmission    bool          `json:"has_submission"`
}

func (q *Queries) UpsertBranding(ctx context.Context, arg UpsertBrandingParams) error {
	_, err := q.db.Exec(ctx, upsertBranding,
		arg.VideoID,
		arg.Title,
		arg.OriginalTitleWon,
		arg.ThumbnailTime,
		arg.OriginalThumbWon,
		arg.RandomTime,
		arg.HasSubmission,
	)
	return err
}
