// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dismissed_videos.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const dismissVideo = `-- name: DismissVideo :exec
INSERT INTO dismissed_videos (user_id, video_id)
VALUES ($1, $2)
ON CONFLICT (user_id, video_id) DO NOTHING
`

type DismissVideoParams struct {
	UserID  uuid.UUID `json:"user_id"`
	VideoID string    `json:"video_id"`
}

// Idempotent: dismissing an already-dismissed video keeps the original time,
// so a double tap does not look like a fresh decision.
func (q *Queries) DismissVideo(ctx context.Context, arg DismissVideoParams) error {
	_, err := q.db.Exec(ctx, dismissVideo, arg.UserID, arg.VideoID)
	return err
}

const listDismissed = `-- name: ListDismissed :many
SELECT video_id FROM dismissed_videos
WHERE user_id = $1
ORDER BY dismissed_at DESC
LIMIT $2
`

type ListDismissedParams struct {
	UserID uuid.UUID `json:"user_id"`
	Lim    int32     `json:"lim"`
}

// Newest first, for the screen that lets a viewer put one back.
func (q *Queries) ListDismissed(ctx context.Context, arg ListDismissedParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listDismissed, arg.UserID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var video_id string
		if err := rows.Scan(&video_id); err != nil {
			return nil, err
		}
		items = append(items, video_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDismissedForVideos = `-- name: ListDismissedForVideos :many
SELECT video_id FROM dismissed_videos
WHERE user_id = $1 AND video_id = ANY($2::text[])
`

type ListDismissedForVideosParams struct {
	UserID   uuid.UUID `json:"user_id"`
	VideoIds []string  `json:"video_ids"`
}

// Which of these videos the user has dismissed — one round trip per page,
// the same shape as ListWatchEventsForVideos.
func (q *Queries) ListDismissedForVideos(ctx context.Context, arg ListDismissedForVideosParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listDismissedForVideos, arg.UserID, arg.VideoIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var video_id string
		if err := rows.Scan(&video_id); err != nil {
			return nil, err
		}
		items = append(items, video_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const undismissVideo = `-- name: UndismissVideo :exec
DELETE FROM dismissed_videos WHERE user_id = $1 AND video_id = $2
`

type UndismissVideoParams struct {
	UserID  uuid.UUID `json:"user_id"`
	VideoID string    `json:"video_id"`
}

func (q *Queries) UndismissVideo(ctx context.Context, arg UndismissVideoParams) error {
	_, err := q.db.Exec(ctx, undismissVideo, arg.UserID, arg.VideoID)
	return err
}
