// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: external_cache.sql

package sqlc

import (
	"context"
)

const listCached = `-- name: ListCached :many
SELECT source, key, payload, has_data, fetched_at FROM external_cache
WHERE source = $1 AND key = ANY($2::text[])
`

type ListCachedParams struct {
	Source string   `json:"source"`
	Keys   []string `json:"keys"`
}

// What is already known for these keys. One query per page, per source.
func (q *Queries) ListCached(ctx context.Context, arg ListCachedParams) ([]ExternalCache, error) {
	rows, err := q.db.Query(ctx, listCached, arg.Source, arg.Keys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExternalCache{}
	for rows.Next() {
		var i ExternalCache
		if err := rows.Scan(
			&i.Source,
			&i.Key,
			&i.Payload,
			&i.HasData,
			&i.FetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCached = `-- name: UpsertCached :exec
INSERT INTO external_cache (source, key, payload, has_data, fetched_at)
VALUES ($1, $2, $3, $4, now())
ON CONFLICT (source, key) DO UPDATE
SET payload    = EXCLUDED.payload,
    has_data   = EXCLUDED.has_data,
    fetched_at = now()
`

type UpsertCachedParams struct {
	Source  string `json:"source"`
	Key     string `json:"key"`
	Payload []byte `json:"payload"`
	HasData bool   `json:"has_data"`
}

func (q *Queries) UpsertCached(ctx context.Context, arg UpsertCachedParams) error {
	_, err := q.db.Exec(ctx, upsertCached,
		arg.Source,
		arg.Key,
		arg.Payload,
		arg.HasData,
	)
	return err
}
