// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: feeds.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const addFeedChannel = `-- name: AddFeedChannel :exec
INSERT INTO feed_channels (feed_id, channel_id, position)
VALUES ($1, $2, $3)
ON CONFLICT (feed_id, channel_id) DO UPDATE SET position = EXCLUDED.position
`

type AddFeedChannelParams struct {
	FeedID    uuid.UUID `json:"feed_id"`
	ChannelID string    `json:"channel_id"`
	Position  int32     `json:"position"`
}

func (q *Queries) AddFeedChannel(ctx context.Context, arg AddFeedChannelParams) error {
	_, err := q.db.Exec(ctx, addFeedChannel, arg.FeedID, arg.ChannelID, arg.Position)
	return err
}

const addFeedPlaylist = `-- name: AddFeedPlaylist :exec
INSERT INTO feed_playlists (feed_id, playlist_id, position)
VALUES ($1, $2, $3)
ON CONFLICT (feed_id, playlist_id) DO UPDATE SET position = EXCLUDED.position
`

type AddFeedPlaylistParams struct {
	FeedID     uuid.UUID `json:"feed_id"`
	PlaylistID string    `json:"playlist_id"`
	Position   int32     `json:"position"`
}

func (q *Queries) AddFeedPlaylist(ctx context.Context, arg AddFeedPlaylistParams) error {
	_, err := q.db.Exec(ctx, addFeedPlaylist, arg.FeedID, arg.PlaylistID, arg.Position)
	return err
}

const createFeed = `-- name: CreateFeed :one
INSERT INTO feeds (user_id, name, sort, hide_seen, include_shorts, subtitles_only, pinned, position, notify, notified_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, CASE WHEN $9::boolean THEN now() END)
RETURNING id, user_id, name, sort, hide_seen, include_shorts, subtitles_only, pinned, position, created_at, updated_at, notify, notified_at
`

type CreateFeedParams struct {
	UserID        uuid.UUID `json:"user_id"`
	Name          string    `json:"name"`
	Sort          string    `json:"sort"`
	HideSeen      bool      `json:"hide_seen"`
	IncludeShorts bool      `json:"include_shorts"`
	SubtitlesOnly bool      `json:"subtitles_only"`
	Pinned        bool      `json:"pinned"`
	Position      int32     `json:"position"`
	Notify        bool      `json:"notify"`
}

// A feed born notifying starts its high-water mark at now: nothing already in
// the archive is news.
func (q *Queries) CreateFeed(ctx context.Context, arg CreateFeedParams) (Feed, error) {
	row := q.db.QueryRow(ctx, createFeed,
		arg.UserID,
		arg.Name,
		arg.Sort,
		arg.HideSeen,
		arg.IncludeShorts,
		arg.SubtitlesOnly,
		arg.Pinned,
		arg.Position,
		arg.Notify,
	)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Sort,
		&i.HideSeen,
		&i.IncludeShorts,
		&i.SubtitlesOnly,
		&i.Pinned,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Notify,
		&i.NotifiedAt,
	)
	return i, err
}

const deleteChannelFromUserFeeds = `-- name: DeleteChannelFromUserFeeds :exec
DELETE FROM feed_channels fc
USING feeds f
WHERE fc.feed_id = f.id AND f.user_id = $1 AND fc.channel_id = $2
`

type DeleteChannelFromUserFeedsParams struct {
	UserID    uuid.UUID `json:"user_id"`
	ChannelID string    `json:"channel_id"`
}

// Removes a channel from every feed the user owns (before re-adding it to the
// selected ones).
func (q *Queries) DeleteChannelFromUserFeeds(ctx context.Context, arg DeleteChannelFromUserFeedsParams) error {
	_, err := q.db.Exec(ctx, deleteChannelFromUserFeeds, arg.UserID, arg.ChannelID)
	return err
}

const deleteFeed = `-- name: DeleteFeed :execrows
DELETE FROM feeds WHERE id = $1 AND user_id = $2
`

type DeleteFeedParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteFeed(ctx context.Context, arg DeleteFeedParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFeed, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteFeedChannels = `-- name: DeleteFeedChannels :exec
DELETE FROM feed_channels WHERE feed_id = $1
`

func (q *Queries) DeleteFeedChannels(ctx context.Context, feedID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteFeedChannels, feedID)
	return err
}

const deleteFeedPlaylists = `-- name: DeleteFeedPlaylists :exec
DELETE FROM feed_playlists WHERE feed_id = $1
`

func (q *Queries) DeleteFeedPlaylists(ctx context.Context, feedID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteFeedPlaylists, feedID)
	return err
}

const deletePlaylistFromUserFeeds = `-- name: DeletePlaylistFromUserFeeds :exec
DELETE FROM feed_playlists fp
USING feeds f
WHERE fp.feed_id = f.id AND f.user_id = $1 AND fp.playlist_id = $2
`

type DeletePlaylistFromUserFeedsParams struct {
	UserID     uuid.UUID `json:"user_id"`
	PlaylistID string    `json:"playlist_id"`
}

// Removes a playlist from every feed the user owns (before re-adding it to
// the selected ones).
func (q *Queries) DeletePlaylistFromUserFeeds(ctx context.Context, arg DeletePlaylistFromUserFeedsParams) error {
	_, err := q.db.Exec(ctx, deletePlaylistFromUserFeeds, arg.UserID, arg.PlaylistID)
	return err
}

const getFeed = `-- name: GetFeed :one
SELECT id, user_id, name, sort, hide_seen, include_shorts, subtitles_only, pinned, position, created_at, updated_at, notify, notified_at FROM feeds WHERE id = $1 AND user_id = $2
`

type GetFeedParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetFeed(ctx context.Context, arg GetFeedParams) (Feed, error) {
	row := q.db.QueryRow(ctx, getFeed, arg.ID, arg.UserID)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Sort,
		&i.HideSeen,
		&i.IncludeShorts,
		&i.SubtitlesOnly,
		&i.Pinned,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Notify,
		&i.NotifiedAt,
	)
	return i, err
}

const listFeedChannels = `-- name: ListFeedChannels :many
SELECT channel_id FROM feed_channels WHERE feed_id = $1 ORDER BY position
`

func (q *Queries) ListFeedChannels(ctx context.Context, feedID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listFeedChannels, feedID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var channel_id string
		if err := rows.Scan(&channel_id); err != nil {
			return nil, err
		}
		items = append(items, channel_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeedChannelsForUser = `-- name: ListFeedChannelsForUser :many
SELECT fc.feed_id, fc.channel_id, fc.position, f.name AS feed_name
FROM feed_channels fc
JOIN feeds f ON f.id = fc.feed_id
WHERE f.user_id = $1
ORDER BY f.position, fc.position
`

type ListFeedChannelsForUserRow struct {
	FeedID    uuid.UUID `json:"feed_id"`
	ChannelID string    `json:"channel_id"`
	Position  int32     `json:"position"`
	FeedName  string    `json:"feed_name"`
}

// Every (feed, channel) membership of the user in one go, so feed lists and
// channel "In feeds:" badges need a single query.
func (q *Queries) ListFeedChannelsForUser(ctx context.Context, userID uuid.UUID) ([]ListFeedChannelsForUserRow, error) {
	rows, err := q.db.Query(ctx, listFeedChannelsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFeedChannelsForUserRow{}
	for rows.Next() {
		var i ListFeedChannelsForUserRow
		if err := rows.Scan(
			&i.FeedID,
			&i.ChannelID,
			&i.Position,
			&i.FeedName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeedPlaylists = `-- name: ListFeedPlaylists :many
SELECT playlist_id FROM feed_playlists WHERE feed_id = $1 ORDER BY position
`

func (q *Queries) ListFeedPlaylists(ctx context.Context, feedID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listFeedPlaylists, feedID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var playlist_id string
		if err := rows.Scan(&playlist_id); err != nil {
			return nil, err
		}
		items = append(items, playlist_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeedPlaylistsForUser = `-- name: ListFeedPlaylistsForUser :many
SELECT fp.feed_id, fp.playlist_id, fp.position, f.name AS feed_name
FROM feed_playlists fp
JOIN feeds f ON f.id = fp.feed_id
WHERE f.user_id = $1
ORDER BY f.position, fp.position
`

type ListFeedPlaylistsForUserRow struct {
	FeedID     uuid.UUID `json:"feed_id"`
	PlaylistID string    `json:"playlist_id"`
	Position   int32     `json:"position"`
	FeedName   string    `json:"feed_name"`
}

// Every (feed, playlist) membership of the user in one go, so feed lists and
// playlist "In feeds:" badges need a single query.
func (q *Queries) ListFeedPlaylistsForUser(ctx context.Context, userID uuid.UUID) ([]ListFeedPlaylistsForUserRow, error) {
	rows, err := q.db.Query(ctx, listFeedPlaylistsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFeedPlaylistsForUserRow{}
	for rows.Next() {
		var i ListFeedPlaylistsForUserRow
		if err := rows.Scan(
			&i.FeedID,
			&i.PlaylistID,
			&i.Position,
			&i.FeedName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeeds = `-- name: ListFeeds :many
SELECT id, user_id, name, sort, hide_seen, include_shorts, subtitles_only, pinned, position, created_at, updated_at, notify, notified_at FROM feeds WHERE user_id = $1 ORDER BY position, created_at
`

func (q *Queries) ListFeeds(ctx context.Context, userID uuid.UUID) ([]Feed, error) {
	rows, err := q.db.Query(ctx, listFeeds, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Feed{}
	for rows.Next() {
		var i Feed
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Sort,
			&i.HideSeen,
			&i.IncludeShorts,
			&i.SubtitlesOnly,
			&i.Pinned,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Notify,
			&i.NotifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextFeedChannelPosition = `-- name: NextFeedChannelPosition :one
SELECT COALESCE(MAX(position), -1)::int + 1 FROM feed_channels WHERE feed_id = $1
`

func (q *Queries) NextFeedChannelPosition(ctx context.Context, feedID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, nextFeedChannelPosition, feedID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const nextFeedPlaylistPosition = `-- name: NextFeedPlaylistPosition :one
SELECT COALESCE(MAX(position), -1)::int + 1 FROM feed_playlists WHERE feed_id = $1
`

func (q *Queries) NextFeedPlaylistPosition(ctx context.Context, feedID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, nextFeedPlaylistPosition, feedID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const nextFeedPosition = `-- name: NextFeedPosition :one
SELECT COALESCE(MAX(position), -1)::int + 1 FROM feeds WHERE user_id = $1
`

func (q *Queries) NextFeedPosition(ctx context.Context, userID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, nextFeedPosition, userID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const setFeedPosition = `-- name: SetFeedPosition :exec
UPDATE feeds SET position = $3, updated_at = now() WHERE id = $1 AND user_id = $2
`

type SetFeedPositionParams struct {
	ID       uuid.UUID `json:"id"`
	UserID   uuid.UUID `json:"user_id"`
	Position int32     `json:"position"`
}

func (q *Queries) SetFeedPosition(ctx context.Context, arg SetFeedPositionParams) error {
	_, err := q.db.Exec(ctx, setFeedPosition, arg.ID, arg.UserID, arg.Position)
	return err
}

const unpinFeeds = `-- name: UnpinFeeds :exec
UPDATE feeds SET pinned = false, updated_at = now() WHERE user_id = $1 AND pinned
`

func (q *Queries) UnpinFeeds(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, unpinFeeds, userID)
	return err
}

const updateFeed = `-- name: UpdateFeed :one
UPDATE feeds
SET name = $3,
    sort = $4,
    hide_seen = $5,
    include_shorts = $6,
    subtitles_only = $7,
    pinned = $8,
    -- Switching notifications on (re)starts the high-water mark at now;
    -- switching them off clears it, so a later switch-on cannot announce
    -- everything that arrived in between.
    notified_at = CASE
        WHEN $9::boolean AND NOT notify THEN now()
        WHEN NOT $9::boolean THEN NULL
        ELSE notified_at
    END,
    notify = $9,
    updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, name, sort, hide_seen, include_shorts, subtitles_only, pinned, position, created_at, updated_at, notify, notified_at
`

type UpdateFeedParams struct {
	ID            uuid.UUID `json:"id"`
	UserID        uuid.UUID `json:"user_id"`
	Name          string    `json:"name"`
	Sort          string    `json:"sort"`
	HideSeen      bool      `json:"hide_seen"`
	IncludeShorts bool      `json:"include_shorts"`
	SubtitlesOnly bool      `json:"subtitles_only"`
	Pinned        bool      `json:"pinned"`
	Notify        bool      `json:"notify"`
}

func (q *Queries) UpdateFeed(ctx context.Context, arg UpdateFeedParams) (Feed, error) {
	row := q.db.QueryRow(ctx, updateFeed,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Sort,
		arg.HideSeen,
		arg.IncludeShorts,
		arg.SubtitlesOnly,
		arg.Pinned,
		arg.Notify,
	)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Sort,
		&i.HideSeen,
		&i.IncludeShorts,
		&i.SubtitlesOnly,
		&i.Pinned,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Notify,
		&i.NotifiedAt,
	)
	return i, err
}
