// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type DismissedVideo struct {
	UserID      uuid.UUID          `json:"user_id"`
	VideoID     string             `json:"video_id"`
	DismissedAt pgtype.Timestamptz `json:"dismissed_at"`
}

type ExternalCache struct {
	Source    string             `json:"source"`
	Key       string             `json:"key"`
	Payload   []byte             `json:"payload"`
	HasData   bool               `json:"has_data"`
	FetchedAt pgtype.Timestamptz `json:"fetched_at"`
}

type Feed struct {
	ID            uuid.UUID          `json:"id"`
	UserID        uuid.UUID          `json:"user_id"`
	Name          string             `json:"name"`
	Sort          string             `json:"sort"`
	HideSeen      bool               `json:"hide_seen"`
	IncludeShorts bool               `json:"include_shorts"`
	SubtitlesOnly bool               `json:"subtitles_only"`
	Pinned        bool               `json:"pinned"`
	Position      int32              `json:"position"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type FeedChannel struct {
	FeedID    uuid.UUID `json:"feed_id"`
	ChannelID string    `json:"channel_id"`
	Position  int32     `json:"position"`
}

type FeedPlaylist struct {
	FeedID     uuid.UUID `json:"feed_id"`
	PlaylistID string    `json:"playlist_id"`
	Position   int32     `json:"position"`
}

type FeedSeriesWatch struct {
	FeedID    uuid.UUID          `json:"feed_id"`
	ChannelID string             `json:"channel_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type PinnedChannel struct {
	UserID    uuid.UUID          `json:"user_id"`
	ChannelID string             `json:"channel_id"`
	Position  int32              `json:"position"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type PlaylistSetting struct {
	UserID     uuid.UUID          `json:"user_id"`
	PlaylistID string             `json:"playlist_id"`
	Position   int32              `json:"position"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	Pinned     bool               `json:"pinned"`
	Music      bool               `json:"music"`
}

type SeriesSeen struct {
	UserID     uuid.UUID          `json:"user_id"`
	ChannelID  string             `json:"channel_id"`
	PlaylistID string             `json:"playlist_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID         uuid.UUID          `json:"id"`
	OidcSub    string             `json:"oidc_sub"`
	Email      pgtype.Text        `json:"email"`
	Name       pgtype.Text        `json:"name"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
}

type UserPref struct {
	UserID    uuid.UUID          `json:"user_id"`
	Prefs     []byte             `json:"prefs"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type WatchEvent struct {
	ID            uuid.UUID          `json:"id"`
	UserID        uuid.UUID          `json:"user_id"`
	VideoID       string             `json:"video_id"`
	ChannelID     string             `json:"channel_id"`
	ChannelName   string             `json:"channel_name"`
	Title         string             `json:"title"`
	FirstPlayedAt pgtype.Timestamptz `json:"first_played_at"`
	LastPlayedAt  pgtype.Timestamptz `json:"last_played_at"`
	Position      float64            `json:"position"`
	Duration      int32              `json:"duration"`
	CompletedAt   pgtype.Timestamptz `json:"completed_at"`
	Hidden        bool               `json:"hidden"`
}
