// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pinned_channels.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const listPinnedChannels = `-- name: ListPinnedChannels :many
SELECT user_id, channel_id, position, created_at FROM pinned_channels WHERE user_id = $1 ORDER BY position, created_at
`

func (q *Queries) ListPinnedChannels(ctx context.Context, userID uuid.UUID) ([]PinnedChannel, error) {
	rows, err := q.db.Query(ctx, listPinnedChannels, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PinnedChannel{}
	for rows.Next() {
		var i PinnedChannel
		if err := rows.Scan(
			&i.UserID,
			&i.ChannelID,
			&i.Position,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pinChannel = `-- name: PinChannel :exec
INSERT INTO pinned_channels (user_id, channel_id, position)
VALUES (
    $1,
    $2,
    COALESCE((SELECT max(position) + 1 FROM pinned_channels WHERE user_id = $1), 0)
)
ON CONFLICT (user_id, channel_id) DO NOTHING
`

type PinChannelParams struct {
	UserID    uuid.UUID `json:"user_id"`
	ChannelID string    `json:"channel_id"`
}

// Appends to the end of the user's pins; re-pinning keeps the position.
func (q *Queries) PinChannel(ctx context.Context, arg PinChannelParams) error {
	_, err := q.db.Exec(ctx, pinChannel, arg.UserID, arg.ChannelID)
	return err
}

const unpinChannel = `-- name: UnpinChannel :exec
DELETE FROM pinned_channels WHERE user_id = $1 AND channel_id = $2
`

type UnpinChannelParams struct {
	UserID    uuid.UUID `json:"user_id"`
	ChannelID string    `json:"channel_id"`
}

func (q *Queries) UnpinChannel(ctx context.Context, arg UnpinChannelParams) error {
	_, err := q.db.Exec(ctx, unpinChannel, arg.UserID, arg.ChannelID)
	return err
}
