// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pinned_playlists.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const listPinnedPlaylists = `-- name: ListPinnedPlaylists :many
SELECT user_id, playlist_id, position, created_at FROM pinned_playlists WHERE user_id = $1 ORDER BY position, created_at
`

func (q *Queries) ListPinnedPlaylists(ctx context.Context, userID uuid.UUID) ([]PinnedPlaylist, error) {
	rows, err := q.db.Query(ctx, listPinnedPlaylists, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PinnedPlaylist{}
	for rows.Next() {
		var i PinnedPlaylist
		if err := rows.Scan(
			&i.UserID,
			&i.PlaylistID,
			&i.Position,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pinPlaylist = `-- name: PinPlaylist :exec
INSERT INTO pinned_playlists (user_id, playlist_id, position)
VALUES (
    $1,
    $2,
    COALESCE((SELECT max(position) + 1 FROM pinned_playlists WHERE user_id = $1), 0)
)
ON CONFLICT (user_id, playlist_id) DO NOTHING
`

type PinPlaylistParams struct {
	UserID     uuid.UUID `json:"user_id"`
	PlaylistID string    `json:"playlist_id"`
}

// Appends to the end of the user's pins. Re-pinning an already pinned
// playlist keeps its position rather than moving it to the end.
func (q *Queries) PinPlaylist(ctx context.Context, arg PinPlaylistParams) error {
	_, err := q.db.Exec(ctx, pinPlaylist, arg.UserID, arg.PlaylistID)
	return err
}

const unpinPlaylist = `-- name: UnpinPlaylist :exec
DELETE FROM pinned_playlists WHERE user_id = $1 AND playlist_id = $2
`

type UnpinPlaylistParams struct {
	UserID     uuid.UUID `json:"user_id"`
	PlaylistID string    `json:"playlist_id"`
}

func (q *Queries) UnpinPlaylist(ctx context.Context, arg UnpinPlaylistParams) error {
	_, err := q.db.Exec(ctx, unpinPlaylist, arg.UserID, arg.PlaylistID)
	return err
}
