// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: playlist_settings.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const listPinnedPlaylists = `-- name: ListPinnedPlaylists :many
SELECT user_id, playlist_id, position, created_at, pinned, music FROM playlist_settings
WHERE user_id = $1 AND pinned
ORDER BY position, created_at
`

func (q *Queries) ListPinnedPlaylists(ctx context.Context, userID uuid.UUID) ([]PlaylistSetting, error) {
	rows, err := q.db.Query(ctx, listPinnedPlaylists, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlaylistSetting{}
	for rows.Next() {
		var i PlaylistSetting
		if err := rows.Scan(
			&i.UserID,
			&i.PlaylistID,
			&i.Position,
			&i.CreatedAt,
			&i.Pinned,
			&i.Music,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlaylistSettings = `-- name: ListPlaylistSettings :many
SELECT user_id, playlist_id, position, created_at, pinned, music FROM playlist_settings WHERE user_id = $1
`

func (q *Queries) ListPlaylistSettings(ctx context.Context, userID uuid.UUID) ([]PlaylistSetting, error) {
	rows, err := q.db.Query(ctx, listPlaylistSettings, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlaylistSetting{}
	for rows.Next() {
		var i PlaylistSetting
		if err := rows.Scan(
			&i.UserID,
			&i.PlaylistID,
			&i.Position,
			&i.CreatedAt,
			&i.Pinned,
			&i.Music,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneEmptyPlaylistSettings = `-- name: PruneEmptyPlaylistSettings :exec
DELETE FROM playlist_settings WHERE user_id = $1 AND NOT pinned AND NOT music
`

// A row with nothing set is noise; drop it so the table only holds intent.
func (q *Queries) PruneEmptyPlaylistSettings(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, pruneEmptyPlaylistSettings, userID)
	return err
}

const setPlaylistMusic = `-- name: SetPlaylistMusic :exec
INSERT INTO playlist_settings (user_id, playlist_id, music, position)
VALUES (
    $1,
    $2,
    $3,
    COALESCE((SELECT max(position) + 1 FROM playlist_settings WHERE user_id = $1), 0)
)
ON CONFLICT (user_id, playlist_id) DO UPDATE SET music = EXCLUDED.music
`

type SetPlaylistMusicParams struct {
	UserID     uuid.UUID `json:"user_id"`
	PlaylistID string    `json:"playlist_id"`
	Music      bool      `json:"music"`
}

func (q *Queries) SetPlaylistMusic(ctx context.Context, arg SetPlaylistMusicParams) error {
	_, err := q.db.Exec(ctx, setPlaylistMusic, arg.UserID, arg.PlaylistID, arg.Music)
	return err
}

const setPlaylistPinned = `-- name: SetPlaylistPinned :exec
INSERT INTO playlist_settings (user_id, playlist_id, pinned, position)
VALUES (
    $1,
    $2,
    $3,
    COALESCE((SELECT max(position) + 1 FROM playlist_settings WHERE user_id = $1), 0)
)
ON CONFLICT (user_id, playlist_id) DO UPDATE SET pinned = EXCLUDED.pinned
`

type SetPlaylistPinnedParams struct {
	UserID     uuid.UUID `json:"user_id"`
	PlaylistID string    `json:"playlist_id"`
	Pinned     bool      `json:"pinned"`
}

// Appends to the end of the user's pins on first insert; re-pinning an
// already pinned playlist keeps its position rather than moving it.
func (q *Queries) SetPlaylistPinned(ctx context.Context, arg SetPlaylistPinnedParams) error {
	_, err := q.db.Exec(ctx, setPlaylistPinned, arg.UserID, arg.PlaylistID, arg.Pinned)
	return err
}
