// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: push_devices.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countPushDevices = `-- name: CountPushDevices :one
SELECT COUNT(*) FROM push_devices WHERE user_id = $1
`

func (q *Queries) CountPushDevices(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPushDevices, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deletePushDevice = `-- name: DeletePushDevice :execrows
DELETE FROM push_devices WHERE token = $1 AND user_id = $2
`

type DeletePushDeviceParams struct {
	Token  string    `json:"token"`
	UserID uuid.UUID `json:"user_id"`
}

// User-scoped: signing out removes the caller's own registration only.
func (q *Queries) DeletePushDevice(ctx context.Context, arg DeletePushDeviceParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePushDevice, arg.Token, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const forgetPushDevice = `-- name: ForgetPushDevice :exec
DELETE FROM push_devices WHERE token = $1
`

// Server-side: APNs said the token is dead, whoever it belonged to.
func (q *Queries) ForgetPushDevice(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, forgetPushDevice, token)
	return err
}

const listNotifyFeeds = `-- name: ListNotifyFeeds :many
SELECT id, user_id, name, sort, hide_seen, include_shorts, subtitles_only, pinned, position, created_at, updated_at, notify, notified_at FROM feeds WHERE notify ORDER BY user_id, position
`

// Every feed of every user that asked to be notified — what the notifier
// walks each pass.
func (q *Queries) ListNotifyFeeds(ctx context.Context) ([]Feed, error) {
	rows, err := q.db.Query(ctx, listNotifyFeeds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Feed{}
	for rows.Next() {
		var i Feed
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Sort,
			&i.HideSeen,
			&i.IncludeShorts,
			&i.SubtitlesOnly,
			&i.Pinned,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Notify,
			&i.NotifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPushDevices = `-- name: ListPushDevices :many
SELECT token, user_id, platform, environment, created_at, updated_at FROM push_devices WHERE user_id = $1 ORDER BY created_at
`

func (q *Queries) ListPushDevices(ctx context.Context, userID uuid.UUID) ([]PushDevice, error) {
	rows, err := q.db.Query(ctx, listPushDevices, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PushDevice{}
	for rows.Next() {
		var i PushDevice
		if err := rows.Scan(
			&i.Token,
			&i.UserID,
			&i.Platform,
			&i.Environment,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setFeedNotifiedAt = `-- name: SetFeedNotifiedAt :exec
UPDATE feeds SET notified_at = $2 WHERE id = $1
`

type SetFeedNotifiedAtParams struct {
	ID         uuid.UUID          `json:"id"`
	NotifiedAt pgtype.Timestamptz `json:"notified_at"`
}

func (q *Queries) SetFeedNotifiedAt(ctx context.Context, arg SetFeedNotifiedAtParams) error {
	_, err := q.db.Exec(ctx, setFeedNotifiedAt, arg.ID, arg.NotifiedAt)
	return err
}

const upsertPushDevice = `-- name: UpsertPushDevice :exec
INSERT INTO push_devices (token, user_id, platform, environment)
VALUES ($1, $2, $3, $4)
ON CONFLICT (token) DO UPDATE
SET user_id = EXCLUDED.user_id,
    platform = EXCLUDED.platform,
    environment = EXCLUDED.environment,
    updated_at = now()
`

type UpsertPushDeviceParams struct {
	Token       string    `json:"token"`
	UserID      uuid.UUID `json:"user_id"`
	Platform    string    `json:"platform"`
	Environment string    `json:"environment"`
}

// A token is a device; registering it again (a new launch, a token Apple
// rotated, a different account on the same phone) moves it to the caller.
func (q *Queries) UpsertPushDevice(ctx context.Context, arg UpsertPushDeviceParams) error {
	_, err := q.db.Exec(ctx, upsertPushDevice,
		arg.Token,
		arg.UserID,
		arg.Platform,
		arg.Environment,
	)
	return err
}
