// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddFeedChannel(ctx context.Context, arg AddFeedChannelParams) error
	AddFeedPlaylist(ctx context.Context, arg AddFeedPlaylistParams) error
	AddSeriesWatch(ctx context.Context, arg AddSeriesWatchParams) error
	CountHistory(ctx context.Context, arg CountHistoryParams) (int64, error)
	CountPushDevices(ctx context.Context, userID uuid.UUID) (int64, error)
	// A feed born notifying starts its high-water mark at now: nothing already in
	// the archive is news.
	CreateFeed(ctx context.Context, arg CreateFeedParams) (Feed, error)
	// Removes a channel from every feed the user owns (before re-adding it to the
	// selected ones).
	DeleteChannelFromUserFeeds(ctx context.Context, arg DeleteChannelFromUserFeedsParams) error
	DeleteFeed(ctx context.Context, arg DeleteFeedParams) (int64, error)
	DeleteFeedChannels(ctx context.Context, feedID uuid.UUID) error
	DeleteFeedPlaylists(ctx context.Context, feedID uuid.UUID) error
	// Removes a playlist from every feed the user owns (before re-adding it to
	// the selected ones).
	DeletePlaylistFromUserFeeds(ctx context.Context, arg DeletePlaylistFromUserFeedsParams) error
	// User-scoped: signing out removes the caller's own registration only.
	DeletePushDevice(ctx context.Context, arg DeletePushDeviceParams) (int64, error)
	DeleteSeriesWatches(ctx context.Context, feedID uuid.UUID) error
	// Idempotent: dismissing an already-dismissed video keeps the original time,
	// so a double tap does not look like a fresh decision.
	DismissVideo(ctx context.Context, arg DismissVideoParams) error
	// Server-side: APNs said the token is dead, whoever it belonged to.
	ForgetPushDevice(ctx context.Context, token string) error
	GetFeed(ctx context.Context, arg GetFeedParams) (Feed, error)
	GetPrefs(ctx context.Context, userID uuid.UUID) ([]byte, error)
	GetUser(ctx context.Context, id uuid.UUID) (User, error)
	GetWatchEvent(ctx context.Context, arg GetWatchEventParams) (WatchEvent, error)
	HideHistoryEntry(ctx context.Context, arg HideHistoryEntryParams) (int64, error)
	// Every playlist anyone has pinned. A pin is one user's, but the derived media
	// is shared, so one person's pin keeps the renditions for everybody.
	ListAllPinnedPlaylists(ctx context.Context) ([]string, error)
	// What is already known for these keys. One query per page, per source.
	ListCached(ctx context.Context, arg ListCachedParams) ([]ExternalCache, error)
	// Newest first, for the screen that lets a viewer put one back.
	ListDismissed(ctx context.Context, arg ListDismissedParams) ([]string, error)
	// Which of these videos the user has dismissed — one round trip per page,
	// the same shape as ListWatchEventsForVideos.
	ListDismissedForVideos(ctx context.Context, arg ListDismissedForVideosParams) ([]string, error)
	ListFeedChannels(ctx context.Context, feedID uuid.UUID) ([]string, error)
	// Every (feed, channel) membership of the user in one go, so feed lists and
	// channel "In feeds:" badges need a single query.
	ListFeedChannelsForUser(ctx context.Context, userID uuid.UUID) ([]ListFeedChannelsForUserRow, error)
	ListFeedPlaylists(ctx context.Context, feedID uuid.UUID) ([]string, error)
	// Every (feed, playlist) membership of the user in one go, so feed lists and
	// playlist "In feeds:" badges need a single query.
	ListFeedPlaylistsForUser(ctx context.Context, userID uuid.UUID) ([]ListFeedPlaylistsForUserRow, error)
	ListFeeds(ctx context.Context, userID uuid.UUID) ([]Feed, error)
	// Of these videos, the ones nobody is part-way through: completed by at least
	// one viewer and in progress for none of them.
	//
	// It asks about a given set rather than listing the whole history because the
	// caller starts from what is on the disk, which is far smaller. `hidden` is
	// deliberately ignored: deleting a video from your history says nothing about
	// whether you finished it, and a hidden row still holds the position that says
	// someone is mid-way.
	ListFinishedVideos(ctx context.Context, videoIds []string) ([]string, error)
	ListHistory(ctx context.Context, arg ListHistoryParams) ([]WatchEvent, error)
	// "Continue watching": started, not finished, newest activity first.
	ListInProgress(ctx context.Context, arg ListInProgressParams) ([]WatchEvent, error)
	// Every feed of every user that asked to be notified — what the notifier
	// walks each pass.
	ListNotifyFeeds(ctx context.Context) ([]Feed, error)
	ListPinnedChannels(ctx context.Context, userID uuid.UUID) ([]PinnedChannel, error)
	ListPinnedPlaylists(ctx context.Context, userID uuid.UUID) ([]PlaylistSetting, error)
	ListPlaylistSettings(ctx context.Context, userID uuid.UUID) ([]PlaylistSetting, error)
	ListPushDevices(ctx context.Context, userID uuid.UUID) ([]PushDevice, error)
	// Every playlist the user already knows for the given channels.
	ListSeriesSeen(ctx context.Context, arg ListSeriesSeenParams) ([]string, error)
	ListSeriesWatches(ctx context.Context, feedID uuid.UUID) ([]string, error)
	ListSeriesWatchesForUser(ctx context.Context, userID uuid.UUID) ([]ListSeriesWatchesForUserRow, error)
	// Every account, for the background jobs that work on everyone's behalf rather
	// than inside one person's request.
	ListUserIDs(ctx context.Context) ([]uuid.UUID, error)
	ListWatchEventsForVideos(ctx context.Context, arg ListWatchEventsForVideosParams) ([]WatchEvent, error)
	MarkSeriesSeen(ctx context.Context, arg MarkSeriesSeenParams) error
	NextFeedChannelPosition(ctx context.Context, feedID uuid.UUID) (int32, error)
	NextFeedPlaylistPosition(ctx context.Context, feedID uuid.UUID) (int32, error)
	NextFeedPosition(ctx context.Context, userID uuid.UUID) (int32, error)
	// Appends to the end of the user's pins; re-pinning keeps the position.
	PinChannel(ctx context.Context, arg PinChannelParams) error
	// A row with nothing set is noise; drop it so the table only holds intent.
	PruneEmptyPlaylistSettings(ctx context.Context, userID uuid.UUID) error
	// "Start over": position back to 0, completion untouched.
	ResetPosition(ctx context.Context, arg ResetPositionParams) error
	SetFeedNotifiedAt(ctx context.Context, arg SetFeedNotifiedAtParams) error
	SetFeedPosition(ctx context.Context, arg SetFeedPositionParams) error
	SetPlaylistMusic(ctx context.Context, arg SetPlaylistMusicParams) error
	// Appends to the end of the user's pins on first insert; re-pinning an
	// already pinned playlist keeps its position rather than moving it.
	SetPlaylistPinned(ctx context.Context, arg SetPlaylistPinnedParams) error
	// Explicit watched toggle. true completes (keeping position); false clears
	// both completion and position. Does not bump last_played_at, so toggling
	// from a list doesn't reorder history.
	SetWatched(ctx context.Context, arg SetWatchedParams) (WatchEvent, error)
	UndismissVideo(ctx context.Context, arg UndismissVideoParams) error
	UnpinChannel(ctx context.Context, arg UnpinChannelParams) error
	UnpinFeeds(ctx context.Context, userID uuid.UUID) error
	UpdateFeed(ctx context.Context, arg UpdateFeedParams) (Feed, error)
	UpsertCached(ctx context.Context, arg UpsertCachedParams) error
	UpsertPrefs(ctx context.Context, arg UpsertPrefsParams) error
	// Heartbeat: creates the event on first play, then moves the position and
	// last_played_at.
	//
	// Completion follows the *current* watch. `completed` sets it (keeping the
	// first completion's timestamp); `restart` clears it, which is what a video
	// being watched again from the start looks like — without that, a video seen
	// once could never hold a resume position again, and every client started it
	// from zero forever. The caller decides what counts as a restart, so a video
	// opened by accident does not undo having seen it; see postProgress.
	// A hidden (deleted-from-history) entry resurfaces on the next play.
	UpsertProgress(ctx context.Context, arg UpsertProgressParams) (WatchEvent, error)
	// A token is a device; registering it again (a new launch, a token Apple
	// rotated, a different account on the same phone) moves it to the caller.
	UpsertPushDevice(ctx context.Context, arg UpsertPushDeviceParams) error
	// Called on every authenticated request from the JWT's sub/email/name. The sub
	// is the stable identity; email/name are refreshed and last_seen_at bumped.
	UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error)
	// When videos are *started*, in the viewer's own timezone — the caller passes
	// the zone because the server's is nobody's business.
	WatchByHour(ctx context.Context, arg WatchByHourParams) ([]WatchByHourRow, error)
	// The last `months` calendar months of activity, oldest first.
	WatchByMonth(ctx context.Context, arg WatchByMonthParams) ([]WatchByMonthRow, error)
	WatchByWeekday(ctx context.Context, arg WatchByWeekdayParams) ([]WatchByWeekdayRow, error)
	WatchTopChannels(ctx context.Context, arg WatchTopChannelsParams) ([]WatchTopChannelsRow, error)
	// Stats: what a viewer's watch history adds up to.
	//
	// One row per (user, video), so "seconds" is the furthest point reached in
	// each video — a finished video counts its whole duration, an abandoned one
	// counts where it stopped, and neither counts a rewatch. It is what the table
	// can honestly answer; see docs/api.md "Watch stats".
	WatchTotals(ctx context.Context, arg WatchTotalsParams) (WatchTotalsRow, error)
}

var _ Querier = (*Queries)(nil)
