// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddFeedChannel(ctx context.Context, arg AddFeedChannelParams) error
	CountHistory(ctx context.Context, arg CountHistoryParams) (int64, error)
	CreateFeed(ctx context.Context, arg CreateFeedParams) (Feed, error)
	// Removes a channel from every feed the user owns (before re-adding it to the
	// selected ones).
	DeleteChannelFromUserFeeds(ctx context.Context, arg DeleteChannelFromUserFeedsParams) error
	DeleteFeed(ctx context.Context, arg DeleteFeedParams) (int64, error)
	DeleteFeedChannels(ctx context.Context, feedID uuid.UUID) error
	// Idempotent: dismissing an already-dismissed video keeps the original time,
	// so a double tap does not look like a fresh decision.
	DismissVideo(ctx context.Context, arg DismissVideoParams) error
	GetFeed(ctx context.Context, arg GetFeedParams) (Feed, error)
	GetPrefs(ctx context.Context, userID uuid.UUID) ([]byte, error)
	GetUser(ctx context.Context, id uuid.UUID) (User, error)
	GetWatchEvent(ctx context.Context, arg GetWatchEventParams) (WatchEvent, error)
	HideHistoryEntry(ctx context.Context, arg HideHistoryEntryParams) (int64, error)
	// Newest first, for the screen that lets a viewer put one back.
	ListDismissed(ctx context.Context, arg ListDismissedParams) ([]string, error)
	// Which of these videos the user has dismissed — one round trip per page,
	// the same shape as ListWatchEventsForVideos.
	ListDismissedForVideos(ctx context.Context, arg ListDismissedForVideosParams) ([]string, error)
	ListFeedChannels(ctx context.Context, feedID uuid.UUID) ([]string, error)
	// Every (feed, channel) membership of the user in one go, so feed lists and
	// channel "In feeds:" badges need a single query.
	ListFeedChannelsForUser(ctx context.Context, userID uuid.UUID) ([]ListFeedChannelsForUserRow, error)
	ListFeeds(ctx context.Context, userID uuid.UUID) ([]Feed, error)
	ListHistory(ctx context.Context, arg ListHistoryParams) ([]WatchEvent, error)
	// "Continue watching": started, not finished, newest activity first.
	ListInProgress(ctx context.Context, arg ListInProgressParams) ([]WatchEvent, error)
	ListPinnedPlaylists(ctx context.Context, userID uuid.UUID) ([]PlaylistSetting, error)
	ListPlaylistSettings(ctx context.Context, userID uuid.UUID) ([]PlaylistSetting, error)
	ListWatchEventsForVideos(ctx context.Context, arg ListWatchEventsForVideosParams) ([]WatchEvent, error)
	NextFeedChannelPosition(ctx context.Context, feedID uuid.UUID) (int32, error)
	NextFeedPosition(ctx context.Context, userID uuid.UUID) (int32, error)
	// A row with nothing set is noise; drop it so the table only holds intent.
	PruneEmptyPlaylistSettings(ctx context.Context, userID uuid.UUID) error
	// "Start over": position back to 0, completion untouched.
	ResetPosition(ctx context.Context, arg ResetPositionParams) error
	SetFeedPosition(ctx context.Context, arg SetFeedPositionParams) error
	SetPlaylistMusic(ctx context.Context, arg SetPlaylistMusicParams) error
	// Appends to the end of the user's pins on first insert; re-pinning an
	// already pinned playlist keeps its position rather than moving it.
	SetPlaylistPinned(ctx context.Context, arg SetPlaylistPinnedParams) error
	// Explicit watched toggle. true completes (keeping position); false clears
	// both completion and position. Does not bump last_played_at, so toggling
	// from a list doesn't reorder history.
	SetWatched(ctx context.Context, arg SetWatchedParams) (WatchEvent, error)
	UndismissVideo(ctx context.Context, arg UndismissVideoParams) error
	UnpinFeeds(ctx context.Context, userID uuid.UUID) error
	UpdateFeed(ctx context.Context, arg UpdateFeedParams) (Feed, error)
	UpsertPrefs(ctx context.Context, arg UpsertPrefsParams) error
	// Heartbeat: creates the event on first play, then moves the position and
	// last_played_at.
	//
	// Completion follows the *current* watch. `completed` sets it (keeping the
	// first completion's timestamp); `restart` clears it, which is what a video
	// being watched again from the start looks like — without that, a video seen
	// once could never hold a resume position again, and every client started it
	// from zero forever. The caller decides what counts as a restart, so a video
	// opened by accident does not undo having seen it; see postProgress.
	// A hidden (deleted-from-history) entry resurfaces on the next play.
	UpsertProgress(ctx context.Context, arg UpsertProgressParams) (WatchEvent, error)
	// Called on every authenticated request from the JWT's sub/email/name. The sub
	// is the stable identity; email/name are refreshed and last_seen_at bumped.
	UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
