// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: series_watches.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const addSeriesWatch = `-- name: AddSeriesWatch :exec
INSERT INTO feed_series_watches (feed_id, channel_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddSeriesWatchParams struct {
	FeedID    uuid.UUID `json:"feed_id"`
	ChannelID string    `json:"channel_id"`
}

func (q *Queries) AddSeriesWatch(ctx context.Context, arg AddSeriesWatchParams) error {
	_, err := q.db.Exec(ctx, addSeriesWatch, arg.FeedID, arg.ChannelID)
	return err
}

const deleteSeriesWatches = `-- name: DeleteSeriesWatches :exec
DELETE FROM feed_series_watches WHERE feed_id = $1
`

func (q *Queries) DeleteSeriesWatches(ctx context.Context, feedID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSeriesWatches, feedID)
	return err
}

const listSeriesSeen = `-- name: ListSeriesSeen :many
SELECT playlist_id FROM series_seen WHERE user_id = $1 AND channel_id = ANY($2::text[])
`

type ListSeriesSeenParams struct {
	UserID     uuid.UUID `json:"user_id"`
	ChannelIds []string  `json:"channel_ids"`
}

// Every playlist the user already knows for the given channels.
func (q *Queries) ListSeriesSeen(ctx context.Context, arg ListSeriesSeenParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listSeriesSeen, arg.UserID, arg.ChannelIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var playlist_id string
		if err := rows.Scan(&playlist_id); err != nil {
			return nil, err
		}
		items = append(items, playlist_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSeriesWatches = `-- name: ListSeriesWatches :many
SELECT channel_id FROM feed_series_watches WHERE feed_id = $1 ORDER BY channel_id
`

func (q *Queries) ListSeriesWatches(ctx context.Context, feedID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listSeriesWatches, feedID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var channel_id string
		if err := rows.Scan(&channel_id); err != nil {
			return nil, err
		}
		items = append(items, channel_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSeriesWatchesForUser = `-- name: ListSeriesWatchesForUser :many
SELECT fw.feed_id, fw.channel_id
FROM feed_series_watches fw
JOIN feeds f ON f.id = fw.feed_id
WHERE f.user_id = $1
`

type ListSeriesWatchesForUserRow struct {
	FeedID    uuid.UUID `json:"feed_id"`
	ChannelID string    `json:"channel_id"`
}

func (q *Queries) ListSeriesWatchesForUser(ctx context.Context, userID uuid.UUID) ([]ListSeriesWatchesForUserRow, error) {
	rows, err := q.db.Query(ctx, listSeriesWatchesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSeriesWatchesForUserRow{}
	for rows.Next() {
		var i ListSeriesWatchesForUserRow
		if err := rows.Scan(&i.FeedID, &i.ChannelID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSeriesSeen = `-- name: MarkSeriesSeen :exec
INSERT INTO series_seen (user_id, channel_id, playlist_id)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type MarkSeriesSeenParams struct {
	UserID     uuid.UUID `json:"user_id"`
	ChannelID  string    `json:"channel_id"`
	PlaylistID string    `json:"playlist_id"`
}

func (q *Queries) MarkSeriesSeen(ctx context.Context, arg MarkSeriesSeenParams) error {
	_, err := q.db.Exec(ctx, markSeriesSeen, arg.UserID, arg.ChannelID, arg.PlaylistID)
	return err
}
