// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getPrefs = `-- name: GetPrefs :one
SELECT prefs FROM user_prefs WHERE user_id = $1
`

func (q *Queries) GetPrefs(ctx context.Context, userID uuid.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, getPrefs, userID)
	var prefs []byte
	err := row.Scan(&prefs)
	return prefs, err
}

const getUser = `-- name: GetUser :one
SELECT id, oidc_sub, email, name, created_at, last_seen_at FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OidcSub,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const listUserIDs = `-- name: ListUserIDs :many
SELECT id FROM users ORDER BY created_at
`

// Every account, for the background jobs that work on everyone's behalf rather
// than inside one person's request.
func (q *Queries) ListUserIDs(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listUserIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPrefs = `-- name: UpsertPrefs :exec
INSERT INTO user_prefs (user_id, prefs, updated_at)
VALUES ($1, $2, now())
ON CONFLICT (user_id) DO UPDATE
SET prefs = EXCLUDED.prefs,
    updated_at = now()
`

type UpsertPrefsParams struct {
	UserID uuid.UUID `json:"user_id"`
	Prefs  []byte    `json:"prefs"`
}

func (q *Queries) UpsertPrefs(ctx context.Context, arg UpsertPrefsParams) error {
	_, err := q.db.Exec(ctx, upsertPrefs, arg.UserID, arg.Prefs)
	return err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (oidc_sub, email, name, last_seen_at)
VALUES ($1, $2, $3, now())
ON CONFLICT (oidc_sub) DO UPDATE
SET email = EXCLUDED.email,
    name = EXCLUDED.name,
    last_seen_at = now()
RETURNING id, oidc_sub, email, name, created_at, last_seen_at
`

type UpsertUserParams struct {
	OidcSub string      `json:"oidc_sub"`
	Email   pgtype.Text `json:"email"`
	Name    pgtype.Text `json:"name"`
}

// Called on every authenticated request from the JWT's sub/email/name. The sub
// is the stable identity; email/name are refreshed and last_seen_at bumped.
func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUser, arg.OidcSub, arg.Email, arg.Name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OidcSub,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}
