// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: watch_events.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const countHistory = `-- name: CountHistory :one
SELECT count(*) FROM watch_events
WHERE user_id = $1
  AND NOT hidden
  AND ($2::text = 'all'
       OR ($2::text = 'seen' AND completed_at IS NOT NULL)
       OR ($2::text = 'in_progress' AND completed_at IS NULL))
  AND (completed_at IS NOT NULL OR position >= $3::float8)
  AND ($4::text = ''
       OR title ILIKE '%' || $4::text || '%'
       OR channel_name ILIKE '%' || $4::text || '%')
`

type CountHistoryParams struct {
	UserID      uuid.UUID `json:"user_id"`
	Filter      string    `json:"filter"`
	MinPosition float64   `json:"min_position"`
	Q           string    `json:"q"`
}

func (q *Queries) CountHistory(ctx context.Context, arg CountHistoryParams) (int64, error) {
	row := q.db.QueryRow(ctx, countHistory,
		arg.UserID,
		arg.Filter,
		arg.MinPosition,
		arg.Q,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getWatchEvent = `-- name: GetWatchEvent :one
SELECT id, user_id, video_id, channel_id, channel_name, title, first_played_at, last_played_at, position, duration, completed_at, hidden FROM watch_events WHERE user_id = $1 AND video_id = $2
`

type GetWatchEventParams struct {
	UserID  uuid.UUID `json:"user_id"`
	VideoID string    `json:"video_id"`
}

func (q *Queries) GetWatchEvent(ctx context.Context, arg GetWatchEventParams) (WatchEvent, error) {
	row := q.db.QueryRow(ctx, getWatchEvent, arg.UserID, arg.VideoID)
	var i WatchEvent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.VideoID,
		&i.ChannelID,
		&i.ChannelName,
		&i.Title,
		&i.FirstPlayedAt,
		&i.LastPlayedAt,
		&i.Position,
		&i.Duration,
		&i.CompletedAt,
		&i.Hidden,
	)
	return i, err
}

const hideHistoryEntry = `-- name: HideHistoryEntry :execrows
UPDATE watch_events SET hidden = true WHERE id = $1 AND user_id = $2
`

type HideHistoryEntryParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) HideHistoryEntry(ctx context.Context, arg HideHistoryEntryParams) (int64, error) {
	result, err := q.db.Exec(ctx, hideHistoryEntry, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listHistory = `-- name: ListHistory :many
SELECT id, user_id, video_id, channel_id, channel_name, title, first_played_at, last_played_at, position, duration, completed_at, hidden FROM watch_events
WHERE user_id = $1
  AND NOT hidden
  AND ($2::text = 'all'
       OR ($2::text = 'seen' AND completed_at IS NOT NULL)
       OR ($2::text = 'in_progress' AND completed_at IS NULL))
  AND (completed_at IS NOT NULL OR position >= $3::float8)
  AND ($4::text = ''
       OR title ILIKE '%' || $4::text || '%'
       OR channel_name ILIKE '%' || $4::text || '%')
ORDER BY last_played_at DESC
LIMIT $6 OFFSET $5
`

type ListHistoryParams struct {
	UserID      uuid.UUID `json:"user_id"`
	Filter      string    `json:"filter"`
	MinPosition float64   `json:"min_position"`
	Q           string    `json:"q"`
	PageOffset  int32     `json:"page_offset"`
	PageLimit   int32     `json:"page_limit"`
}

func (q *Queries) ListHistory(ctx context.Context, arg ListHistoryParams) ([]WatchEvent, error) {
	rows, err := q.db.Query(ctx, listHistory,
		arg.UserID,
		arg.Filter,
		arg.MinPosition,
		arg.Q,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WatchEvent{}
	for rows.Next() {
		var i WatchEvent
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.VideoID,
			&i.ChannelID,
			&i.ChannelName,
			&i.Title,
			&i.FirstPlayedAt,
			&i.LastPlayedAt,
			&i.Position,
			&i.Duration,
			&i.CompletedAt,
			&i.Hidden,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInProgress = `-- name: ListInProgress :many
SELECT id, user_id, video_id, channel_id, channel_name, title, first_played_at, last_played_at, position, duration, completed_at, hidden FROM watch_events
WHERE user_id = $1 AND NOT hidden AND completed_at IS NULL AND position > 0
ORDER BY last_played_at DESC
LIMIT $2
`

type ListInProgressParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
}

// "Continue watching": started, not finished, newest activity first.
func (q *Queries) ListInProgress(ctx context.Context, arg ListInProgressParams) ([]WatchEvent, error) {
	rows, err := q.db.Query(ctx, listInProgress, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WatchEvent{}
	for rows.Next() {
		var i WatchEvent
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.VideoID,
			&i.ChannelID,
			&i.ChannelName,
			&i.Title,
			&i.FirstPlayedAt,
			&i.LastPlayedAt,
			&i.Position,
			&i.Duration,
			&i.CompletedAt,
			&i.Hidden,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWatchEventsForVideos = `-- name: ListWatchEventsForVideos :many
SELECT id, user_id, video_id, channel_id, channel_name, title, first_played_at, last_played_at, position, duration, completed_at, hidden FROM watch_events WHERE user_id = $1 AND video_id = ANY($2::text[])
`

type ListWatchEventsForVideosParams struct {
	UserID   uuid.UUID `json:"user_id"`
	VideoIds []string  `json:"video_ids"`
}

func (q *Queries) ListWatchEventsForVideos(ctx context.Context, arg ListWatchEventsForVideosParams) ([]WatchEvent, error) {
	rows, err := q.db.Query(ctx, listWatchEventsForVideos, arg.UserID, arg.VideoIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WatchEvent{}
	for rows.Next() {
		var i WatchEvent
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.VideoID,
			&i.ChannelID,
			&i.ChannelName,
			&i.Title,
			&i.FirstPlayedAt,
			&i.LastPlayedAt,
			&i.Position,
			&i.Duration,
			&i.CompletedAt,
			&i.Hidden,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetPosition = `-- name: ResetPosition :exec
UPDATE watch_events SET position = 0 WHERE user_id = $1 AND video_id = $2
`

type ResetPositionParams struct {
	UserID  uuid.UUID `json:"user_id"`
	VideoID string    `json:"video_id"`
}

// "Start over": position back to 0, completion untouched.
func (q *Queries) ResetPosition(ctx context.Context, arg ResetPositionParams) error {
	_, err := q.db.Exec(ctx, resetPosition, arg.UserID, arg.VideoID)
	return err
}

const setWatched = `-- name: SetWatched :one
INSERT INTO watch_events (user_id, video_id, channel_id, channel_name, title, duration, position, completed_at)
VALUES ($1, $2, $3, $4, $5, $6, 0, CASE WHEN $7::bool THEN now() END)
ON CONFLICT (user_id, video_id) DO UPDATE
SET completed_at = CASE WHEN $7::bool THEN COALESCE(watch_events.completed_at, now()) END,
    position = CASE WHEN $7::bool THEN watch_events.position ELSE 0 END,
    duration = CASE WHEN EXCLUDED.duration > 0 THEN EXCLUDED.duration ELSE watch_events.duration END
RETURNING id, user_id, video_id, channel_id, channel_name, title, first_played_at, last_played_at, position, duration, completed_at, hidden
`

type SetWatchedParams struct {
	UserID      uuid.UUID `json:"user_id"`
	VideoID     string    `json:"video_id"`
	ChannelID   string    `json:"channel_id"`
	ChannelName string    `json:"channel_name"`
	Title       string    `json:"title"`
	Duration    int32     `json:"duration"`
	Watched     bool      `json:"watched"`
}

// Explicit watched toggle. true completes (keeping position); false clears
// both completion and position. Does not bump last_played_at, so toggling
// from a list doesn't reorder history.
func (q *Queries) SetWatched(ctx context.Context, arg SetWatchedParams) (WatchEvent, error) {
	row := q.db.QueryRow(ctx, setWatched,
		arg.UserID,
		arg.VideoID,
		arg.ChannelID,
		arg.ChannelName,
		arg.Title,
		arg.Duration,
		arg.Watched,
	)
	var i WatchEvent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.VideoID,
		&i.ChannelID,
		&i.ChannelName,
		&i.Title,
		&i.FirstPlayedAt,
		&i.LastPlayedAt,
		&i.Position,
		&i.Duration,
		&i.CompletedAt,
		&i.Hidden,
	)
	return i, err
}

const upsertProgress = `-- name: UpsertProgress :one
INSERT INTO watch_events (user_id, video_id, channel_id, channel_name, title, position, duration, completed_at, hidden)
VALUES ($1, $2, $3, $4, $5, $6, $7, CASE WHEN $8::bool THEN now() END, false)
ON CONFLICT (user_id, video_id) DO UPDATE
SET position = EXCLUDED.position,
    duration = EXCLUDED.duration,
    channel_id = EXCLUDED.channel_id,
    channel_name = EXCLUDED.channel_name,
    title = EXCLUDED.title,
    last_played_at = now(),
    completed_at = CASE
        WHEN $8::bool THEN COALESCE(watch_events.completed_at, now())
        WHEN $9::bool THEN NULL
        ELSE watch_events.completed_at
    END,
    hidden = false
RETURNING id, user_id, video_id, channel_id, channel_name, title, first_played_at, last_played_at, position, duration, completed_at, hidden
`

type UpsertProgressParams struct {
	UserID      uuid.UUID `json:"user_id"`
	VideoID     string    `json:"video_id"`
	ChannelID   string    `json:"channel_id"`
	ChannelName string    `json:"channel_name"`
	Title       string    `json:"title"`
	Position    float64   `json:"position"`
	Duration    int32     `json:"duration"`
	Completed   bool      `json:"completed"`
	Restart     bool      `json:"restart"`
}

// Heartbeat: creates the event on first play, then moves the position and
// last_played_at.
//
// Completion follows the *current* watch. `completed` sets it (keeping the
// first completion's timestamp); `restart` clears it, which is what a video
// being watched again from the start looks like — without that, a video seen
// once could never hold a resume position again, and every client started it
// from zero forever. The caller decides what counts as a restart, so a video
// opened by accident does not undo having seen it; see postProgress.
// A hidden (deleted-from-history) entry resurfaces on the next play.
func (q *Queries) UpsertProgress(ctx context.Context, arg UpsertProgressParams) (WatchEvent, error) {
	row := q.db.QueryRow(ctx, upsertProgress,
		arg.UserID,
		arg.VideoID,
		arg.ChannelID,
		arg.ChannelName,
		arg.Title,
		arg.Position,
		arg.Duration,
		arg.Completed,
		arg.Restart,
	)
	var i WatchEvent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.VideoID,
		&i.ChannelID,
		&i.ChannelName,
		&i.Title,
		&i.FirstPlayedAt,
		&i.LastPlayedAt,
		&i.Position,
		&i.Duration,
		&i.CompletedAt,
		&i.Hidden,
	)
	return i, err
}
